# **AI Community Pakistan Linkedin**
[![LinkedIn](https://img.icons8.com/color/48/000000/linkedin.png)](https://www.linkedin.com/company/aicommunitypakistan/?lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_all%3ByA3ec4yFR22MbTcVPUhSBA%3D%3D)


# **My Linkedin and Twitter profile**
[![LinkedIn](https://img.icons8.com/color/48/000000/linkedin.png)](www.linkedin.com/in/haseeb-ahmad-160845286)
[![Twitter](https://img.icons8.com/color/48/000000/twitter.png)](https://twitter.com/haseebyosafxai)

# Introduction of numpy

**NumPy:**

NumPy is like a magic wand for numbers in Python. It helps you do math stuff super fast. Imagine you have a bag of mangoes (numbers), and NumPy makes it easy to count, add, or even share them among friends (operations). So, if you're into numbers, NumPy is your cool math buddy in Python! 🧙‍♂️🔢

- **1st of all we import library**

In [1]:
import numpy as np

> **Task 1:**

In [2]:
# Create an array of even integers from 30 to 70
#Is function ke parameters hote hain (start, stop, step)

even_array = np.arange(30, 71, 2)

# Display the result
print("Array of even integers from 30 to 70:", even_array)


Array of even integers from 30 to 70: [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


> **Task 2:**

- 15 random numbers from a standard normal distribution means making a group of 15 good random numbers that follow a specific bell-shaped graph, called normal distribution. Each number's place shows how it relates to the average.

In [3]:
# 15 random numbers standard normal distribution se banayein
random_numbers = np.random.randn(15)

# Result console pe dikhayein
print("Array of 15 random numbers from a standard normal distribution:", random_numbers)

Array of 15 random numbers from a standard normal distribution: [ 1.21531899 -0.55823211  2.42934469  1.15411582  1.71777671 -0.14977588
 -0.51550533 -0.4825847   1.13640262  0.27721158  0.20915663  0.16340575
 -0.45900307 -0.17987457  0.17119996]


> **Task 3:**

In [4]:
# the cross-product of two matrices
matrix_A = np.array([[1, 2], [3, 4]])
matrix_B = np.array([[5, 6], [7, 8]])
cross_product_result = np.cross(matrix_A, matrix_B)


print("Cross-product of two matrices:",cross_product_result)


Cross-product of two matrices: [-4 -4]


> **How cross product works?**
- matrix_A:
    [[1, 2],
    [3, 4]]

- matrix_B:
    [[5, 6],
    [7, 8]]


- = (1 * 6) - (2 * 5) && (3 * 8) - (4 * 7)
- = (6 - 10)  && (24 - 28)
- = -4 , -4

> **Task 4:**

In [5]:
# Compute the determinant of an array
matrix_C = np.array([[1, 2], [3, 4]])
determinant_result = np.linalg.det(matrix_C)

print("Determinant of the array:",determinant_result)


Determinant of the array: -2.0000000000000004


> **Task 5:**

In [6]:
# Create a 3x3x3 array with random values
# for 3d array the parameters of function are (x,y,z)
random_3d_array = np.random.random((3, 3, 3))

# Display the result
print("3x3x3 array with random values:",random_3d_array)

3x3x3 array with random values: [[[0.53789654 0.07135482 0.18934877]
  [0.35108843 0.15510582 0.10795406]
  [0.87562663 0.12639232 0.91584993]]

 [[0.07027426 0.79804778 0.73397327]
  [0.35391661 0.96717649 0.14172935]
  [0.58744692 0.14033932 0.02555566]]

 [[0.43649529 0.88339258 0.27213173]
  [0.59282678 0.3074973  0.15976251]
  [0.91269801 0.41900253 0.95397535]]]


> **Task 6:**

In [7]:
# Create a 5x5 array with random values
# this is 2d array the function parameters is (x,y)
random_2d_array = np.random.random((5, 5))

# Find the minimum and maximum values
min_value = np.min(random_2d_array)
max_value = np.max(random_2d_array)

print("5x5 array with random values:",random_2d_array)
print("Minimum value:", min_value)
print("Maximum value:", max_value)



5x5 array with random values: [[0.4770715  0.84329897 0.27968043 0.16722164 0.59624805]
 [0.76186069 0.70603653 0.42094825 0.62356054 0.52481813]
 [0.25724629 0.01301024 0.68612195 0.86790356 0.9201397 ]
 [0.1185925  0.9332868  0.34579043 0.27801941 0.80160907]
 [0.62931647 0.84090954 0.94664784 0.07861147 0.38490177]]
Minimum value: 0.013010236032909184
Maximum value: 0.9466478422726164


> **Task 7:**

- **Standard Deviation:** A measure of how spread out numbers are in a dataset.
- **Mean:** The average of a set of numbers, obtained by dividing the sum of all values by the total count.
- **Variance:** A measure of how much each number in a dataset differs from the mean, squared and averaged.

In [8]:
# Compute the mean, standard deviation, and variance along the second axis
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mean = np.mean(array, axis=1)
std = np.std(array, axis=1)
variance = np.var(array, axis=1)

print(f''' Mean along the second axis: {mean} \n Standard deviation along the second axis: {std} \n Variance along the second axis:{variance}''')


 Mean along the second axis: [2. 5. 8.] 
 Standard deviation along the second axis: [0.81649658 0.81649658 0.81649658] 
 Variance along the second axis:[0.66666667 0.66666667 0.66666667]
